"""add is_learned to words

Revision ID: 1605fb67e5d5
Revises: 50c6d8041c3c
Create Date: 2026-06-18 13:00:21.521837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1605fb67e5d5'
down_revision: Union[str, Sequence[str], None] = '50c6d8041c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('is_learned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'is_learned')
    # ### end Alembic commands ###
